project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Ancient Metagenomics"
  author: "James Fellows Yates"
  date: "07/05/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: Theory
      chapters:
        - introduction-to-ngs-sequencing.qmd
        - introduction-to-ancient-dna.qmd
        - introduction-to-metagenomics.qmd
        - introduction-to-microbial-genomics.qmd
        - introduction-to-evolutionary-biology.qmd
    - part: Useful Skills
      chapters:
        - bare-bones-bash.qmd
        - introduction-to-r.qmd
        - introduction-to-python.qmd
        - introduction-to-git.qmd
    - summary.qmd
    - references.qmd
    - acknowledgements.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

