project:
  type: book
  output-dir: docs
  preview:
    port: 4200

book:
  title: "Introduction to Ancient Metagenomics"
  editor: "James Fellows Yates"
  date: "07/05/2023"
  license: "CC-BY 4.0"
  page-footer: "© 2023 SPAAM Community & Authors with ❤️. Available under [CC-BY 4.0](http://creativecommons.org/licenses/by-sa/4.0/). Source material [here](https://github.com/SPAAM-community/intro-to-ancient-metagenomics-book)."
  page-navigation: true
  downloads: [pdf, epub]
  site-url: https://spaam-community.github.io/intro-to-ancient-metagenomics-book
  #cookie-consent:
  #type: express
  reader-mode: true
  chapters:
    - index.qmd
    - citing-this-book.qmd
    - authors.qmd
    - acknowledgements.qmd
    - before-you-start.qmd
    - part: section-theory.qmd
      chapters:
        - introduction-to-ngs-sequencing.qmd
        - introduction-to-ancient-dna.qmd
        - introduction-to-metagenomics.qmd
        - introduction-to-microbial-genomics.qmd
        - introduction-to-evolutionary-biology.qmd
    - part: section-useful-skills.qmd
      chapters:
        - bare-bones-bash.qmd
        - r-tidyverse.qmd
        - python-pandas.qmd
        - git-github.qmd
    - part: section-ancient-metagenomics.qmd
      chapters:
        - taxonomic-profiling.qmd
        - functional-profiling.qmd
        - denovo-assembly.qmd
        - authentication-decontamination.qmd
    - part: section-ancient-genomics.qmd
      chapters:
        - genome-mapping.qmd
        - phylogenomics.qmd
    - part: section-ancient-metagenomic-resources.qmd
      chapters:
        - accessing-ancientmetagenomic-data.qmd
        - ancient-metagenomic-pipelines.qmd
    - summary.qmd
    - part: appendices.qmd
      chapters:
        - resources.qmd
        - references.qmd
        - tools.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
  # pdf:
  #   documentclass: book
  #   include-in-header:
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body:
  #     text: |
  #       \printindex
  #   toc: true
  #   toc-depth: 2
  #   number-depth: 3
  #   highlight-style: github
  #   number-sections: true
  #   colorlinks: true
  #   fontfamily: libertinus
  #   fontfamilyoptions:
  #     - osf
  #     - p

editor: visual
